service: aws-lambda-crud-node
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true	

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:*        
        Resource: 
          - ${env:TABLE_ARN}
	
resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  swapi:
    handler: src/routes/swapi.handler
    events:
      - httpApi:
          path: /api/swapi/{entity}
          method: get
      - httpApi:
          path: /api/swapi/{entity}/{id}
          method: get
  addTask:
    handler: src/routes/addTask.handler
    events:
      - httpApi:
          path: /api/tasks
          method: post
  getTasks:
    handler: src/routes/getTasks.handler
    events:
      - httpApi:
          path: /api/tasks
          method: get
  getTask:
    handler: src/routes/getTask.handler
    events:
      - httpApi:
          path: /api/tasks/{id}
          method: get
  updateTask:
    handler: src/routes/updateTask.handler
    events:
      - httpApi:
          path: /api/tasks/{id}
          method: put
  deleteTask:
    handler: src/routes/deleteTask.handler
    events:
      - httpApi:
          path: /api/tasks/{id}
          method: delete
  