export const swapiTranslations = {
  name: 'nombre',
  height: 'altura',
  mass: 'masa',
  hair_color: 'color_de_cabello',
  skin_color: 'color_de_piel',
  eye_color: 'color_de_ojos',
  birth_year: 'anio_de_nacimiento',
  gender: 'genero',
  homeworld: 'mundo_natal',
  films: 'peliculas',
  species: 'especies',
  vehicles: 'vehiculos',
  starships: 'naves_estelares',
  created: 'creado',
  edited: 'editado',
  url: 'url',
  detail: 'detalle',
  episode_id: 'id_episodio',
  opening_crawl: 'apertura_de_la_pelicula',
  director: 'director',
  producer: 'productor',
  release_date: 'fecha_de_estreno',
  characters: 'personajes',
  planets: 'planetas',
  naves_estelares: 'naves_estelares',
  vehiculos: 'vehiculos',
  especies: 'especies',
  rotation_period: 'periodo_de_rotacion',
  orbital_period: 'periodo_orbital',
  diameter: 'diametro',
  climate: 'clima',
  gravity: 'gravedad',
  terrain: 'terreno',
  surface_water: 'agua_superficial',
  population: 'poblacion',
  residents: 'residentes',
  classification: 'clasificacion',
  designation: 'designacion',
  average_height: 'altura_promedio',
  skin_colors: 'colores_de_piel',
  hair_colors: 'colores_de_cabello',
  eye_colors: 'colores_de_ojos',
  average_lifespan: 'esperanza_de_vida_promedio',
  language: 'idioma',
  people: 'personas',
  peliculas: 'peliculas',
  model: 'modelo',
  manufacturer: 'fabricante',
  cost_in_credits: 'costo_en_creditos',
  length: 'longitud',
  max_atmosphering_speed: 'velocidad_maxima_en_la_atmosfera',
  crew: 'tripulacion',
  passengers: 'pasajeros',
  cargo_capacity: 'capacidad_de_carga',
  consumables: 'consumibles',
  hyperdrive_rating: 'clasificacion_del_hiperimpulsor',
  MGLT: 'MGLT',
  starship_class: 'clase_de_nave_estelar',
  pilots: 'pilotos',
  creado: 'creado',
  editado: 'editado',
};

export const swapiEntities = [
  "films",
  "people",
  "planets",
  "species",
  "starships",
  "vehicles"
]

export const BASE_SWAPI_API = 'https://swapi.py4e.com/api'